-- =============================================================================
-- ticket
-- A Celerant delivery or pickup order imported/entered here so that warehouse
-- staff can scan items out of inventory against it.
-- This system does NOT originate tickets — it processes them.
-- Depends on: store, user
-- =============================================================================
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS ticket;
CREATE TABLE IF NOT EXISTS ticket (
    id            INT UNSIGNED      AUTO_INCREMENT,
    store_id      SMALLINT UNSIGNED NOT NULL,
    reference     VARCHAR(50)       NULL     COMMENT 'e.g. TKT-207-0426-001; generated by app',
    ticket_type   ENUM('Delivery','Pickup') NOT NULL,
    celerant_ref  VARCHAR(100)      NULL     COMMENT 'Celerant order / ticket reference',
    customer_name VARCHAR(200)      NOT NULL,
    scheduled_at  DATETIME          NULL,
    status        ENUM('Pending','Completed','Cancelled') NOT NULL DEFAULT 'Pending',
    completed_by  INT UNSIGNED      NULL,
    completed_at  DATETIME          NULL,
    created_by    INT UNSIGNED      NOT NULL,
    created_at    DATETIME          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    params       JSON               NULL     COMMENT 'Plugin extension data',
    PRIMARY KEY (id),
    UNIQUE KEY uq_ticket_reference (reference),
    KEY idx_ticket_store_status (store_id, status),
    CONSTRAINT fk_ticket_store        FOREIGN KEY (store_id)    REFERENCES store (store_number),
    CONSTRAINT fk_ticket_completed_by FOREIGN KEY (completed_by) REFERENCES `user`  (id),
    CONSTRAINT fk_ticket_created_by   FOREIGN KEY (created_by)  REFERENCES `user`  (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
