-- =============================================================================
-- transfer
-- An inter-store transfer initiated by the sending store.
-- Items are removed from the source store's inventory when the transfer is
-- completed.  Receipt confirmation at the destination store is out of scope for
-- v1.
-- Depends on: store, user
-- =============================================================================
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS transfer;
CREATE TABLE IF NOT EXISTS transfer (
    id            INT UNSIGNED      AUTO_INCREMENT,
    from_store_id SMALLINT UNSIGNED NOT NULL,
    to_store_id   SMALLINT UNSIGNED NOT NULL,
    reference     VARCHAR(50)       NULL     COMMENT 'e.g. XFER-207-0426-001; generated by app',
    notes         TEXT              NULL,
    status        ENUM('Pending','Completed','Cancelled') NOT NULL DEFAULT 'Pending',
    completed_by  INT UNSIGNED      NULL,
    completed_at  DATETIME          NULL,
    created_by    INT UNSIGNED      NOT NULL,
    created_at    DATETIME          NOT NULL DEFAULT CURRENT_TIMESTAMP,
    params       JSON               NULL     COMMENT 'Plugin extension data',
    PRIMARY KEY (id),
    UNIQUE KEY uq_transfer_reference (reference),
    KEY idx_transfer_from_status (from_store_id, status),
    CONSTRAINT fk_xfer_from_store   FOREIGN KEY (from_store_id) REFERENCES store (store_number),
    CONSTRAINT fk_xfer_to_store     FOREIGN KEY (to_store_id)   REFERENCES store (store_number),
    CONSTRAINT fk_xfer_completed_by FOREIGN KEY (completed_by)  REFERENCES `user`  (id),
    CONSTRAINT fk_xfer_created_by   FOREIGN KEY (created_by)    REFERENCES `user`  (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;
