<?php

declare(strict_types=1);

namespace Ims\Migration;

use Ims\Migration\Column\Enum;
use PhpDb\Adapter\AdapterInterface;
use PhpDb\Sql\Argument\Literal as ArgLiteral;
use PhpDb\Sql\Ddl\Column\Datetime;
use PhpDb\Sql\Ddl\Column\Integer;
use PhpDb\Sql\Ddl\Column\Json;
use PhpDb\Sql\Ddl\Column\SmallInteger;
use PhpDb\Sql\Ddl\Column\Varchar;
use PhpDb\Sql\Ddl\Constraint\ForeignKey;
use PhpDb\Sql\Ddl\Constraint\PrimaryKey;
use PhpDb\Sql\Ddl\Constraint\UniqueKey;
use PhpDb\Sql\Ddl\CreateTable;
use PhpDb\Sql\Ddl\DropTable;
use PhpDb\Sql\Ddl\Index\Index;
use PhpDb\Sql\Literal;
use PhpDb\Sql\Sql;

final class Migration010Ticket implements MigrationInterface
{
    public function getStep(): int
    {
        return 10;
    }

    public function getDescription(): string
    {
        return 'Create ticket table';
    }

    public function up(AdapterInterface $adapter): void
    {
        $sql    = new Sql($adapter);
        $create = new CreateTable('ticket');
        $create->ifNotExists();

        $create->addColumn(
            (new Integer('id', nullable: false))
                ->setOptions(['unsigned' => true, 'autoincrement' => true])
        );

        $create->addColumn(
            (new SmallInteger('store_id', nullable: false))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(
            (new Varchar('reference', 50, nullable: true))
                ->setOptions(['comment' => 'e.g. TKT-207-0426-001; generated by app'])
        );

        $create->addColumn(new Enum('ticket_type', ['Delivery', 'Pickup']));

        $create->addColumn(
            (new Varchar('celerant_ref', 100, nullable: true))
                ->setOptions(['comment' => 'Celerant order / ticket reference'])
        );

        $create->addColumn(new Varchar('customer_name', 200));
        $create->addColumn(new Datetime('scheduled_at', nullable: true));

        $create->addColumn(
            new Enum('status', ['Pending', 'Completed', 'Cancelled'], nullable: false, default: 'Pending')
        );

        $create->addColumn(
            (new Integer('completed_by', nullable: true))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(new Datetime('completed_at', nullable: true));

        $create->addColumn(
            (new Integer('created_by', nullable: false))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(
            new Datetime('created_at', nullable: false, default: new ArgLiteral('CURRENT_TIMESTAMP'))
        );

        $create->addColumn(
            (new Json('params', nullable: true))
                ->setOptions(['comment' => 'Plugin extension data'])
        );

        $create->addConstraint(new PrimaryKey('id'));
        $create->addConstraint(new UniqueKey('reference', 'uq_ticket_reference'));
        $create->addConstraint(new Index(['store_id', 'status'], 'idx_ticket_store_status'));
        $create->addConstraint(new ForeignKey('fk_ticket_store', 'store_id', 'store', 'store_number'));
        $create->addConstraint(new ForeignKey('fk_ticket_completed_by', 'completed_by', 'user', 'id'));
        $create->addConstraint(new ForeignKey('fk_ticket_created_by', 'created_by', 'user', 'id'));

        $create->setOptions([
            'engine'          => new Literal('InnoDB'),
            'default charset' => new Literal('utf8mb4'),
            'collate'         => new Literal('utf8mb4_unicode_ci'),
        ]);

        $adapter->query(
            $sql->buildSqlString($create),
            AdapterInterface::QUERY_MODE_EXECUTE
        );
    }

    public function down(AdapterInterface $adapter): void
    {
        $sql = new Sql($adapter);

        $adapter->query(
            $sql->buildSqlString((new DropTable('ticket'))->ifExists()),
            AdapterInterface::QUERY_MODE_EXECUTE
        );
    }
}
