<?php

declare(strict_types=1);

namespace Ims\Migration;

use Ims\Migration\Column\Enum;
use PhpDb\Adapter\AdapterInterface;
use PhpDb\Sql\Argument\Literal as ArgLiteral;
use PhpDb\Sql\Ddl\Column\Datetime;
use PhpDb\Sql\Ddl\Column\Integer;
use PhpDb\Sql\Ddl\Column\Json;
use PhpDb\Sql\Ddl\Column\SmallInteger;
use PhpDb\Sql\Ddl\Column\Text;
use PhpDb\Sql\Ddl\Column\Varchar;
use PhpDb\Sql\Ddl\Constraint\ForeignKey;
use PhpDb\Sql\Ddl\Constraint\PrimaryKey;
use PhpDb\Sql\Ddl\Constraint\UniqueKey;
use PhpDb\Sql\Ddl\CreateTable;
use PhpDb\Sql\Ddl\DropTable;
use PhpDb\Sql\Ddl\Index\Index;
use PhpDb\Sql\Literal;
use PhpDb\Sql\Sql;

final class Migration012Transfer implements MigrationInterface
{
    public function getStep(): int
    {
        return 12;
    }

    public function getDescription(): string
    {
        return 'Create transfer table';
    }

    public function up(AdapterInterface $adapter): void
    {
        $sql    = new Sql($adapter);
        $create = new CreateTable('transfer');
        $create->ifNotExists();

        $create->addColumn(
            (new Integer('id', nullable: false))
                ->setOptions(['unsigned' => true, 'autoincrement' => true])
        );

        $create->addColumn(
            (new SmallInteger('fromStoreId', nullable: false))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(
            (new SmallInteger('toStoreId', nullable: false))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(
            (new Varchar('reference', 50, nullable: true))
                ->setOptions(['comment' => 'e.g. XFER-207-0426-001; generated by app'])
        );

        $create->addColumn(new Text('notes', nullable: true));

        $create->addColumn(
            new Enum('status', ['Pending', 'Completed', 'Cancelled'], nullable: false, default: 'Pending')
        );

        $create->addColumn(
            (new Integer('completedBy', nullable: true))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(new Datetime('completedAt', nullable: true));

        $create->addColumn(
            (new Integer('createdBy', nullable: false))
                ->setOptions(['unsigned' => true])
        );

        $create->addColumn(
            new Datetime('created_at', nullable: false, default: new ArgLiteral('CURRENT_TIMESTAMP'))
        );

        $create->addColumn(
            (new Json('params', nullable: true))
                ->setOptions(['comment' => 'Plugin extension data'])
        );

        $create->addConstraint(new PrimaryKey('id'));
        $create->addConstraint(new UniqueKey('reference', 'uq_transfer_reference'));
        $create->addConstraint(new Index(['fromStoreId', 'status'], 'idx_transfer_from_status'));
        $create->addConstraint(new ForeignKey('fk_xfer_from_store', 'fromStoreId', 'store', 'store_number'));
        $create->addConstraint(new ForeignKey('fk_xfer_to_store', 'toStoreId', 'store', 'store_number'));
        $create->addConstraint(new ForeignKey('fk_xfer_completed_by', 'completedBy', 'user', 'id'));
        $create->addConstraint(new ForeignKey('fk_xfer_created_by', 'createdBy', 'user', 'id'));

        $create->setOptions([
            'engine'          => new Literal('InnoDB'),
            'default charset' => new Literal('utf8mb4'),
            'collate'         => new Literal('utf8mb4_unicode_ci'),
        ]);

        $adapter->query(
            $sql->buildSqlString($create),
            AdapterInterface::QUERY_MODE_EXECUTE
        );
    }

    public function down(AdapterInterface $adapter): void
    {
        $sql = new Sql($adapter);

        $adapter->query(
            $sql->buildSqlString((new DropTable('transfer'))->ifExists()),
            AdapterInterface::QUERY_MODE_EXECUTE
        );
    }
}
