<?php

declare(strict_types=1);

namespace Webware\ConfigManager;

use Brick\VarExporter\ExportException;
use Brick\VarExporter\VarExporter;
use Laminas\ConfigAggregator\ConfigAggregator;
use Webimpress\SafeWriter\Exception\ExceptionInterface as FileWriterException;
use Webimpress\SafeWriter\FileWriter;

use function array_is_list;
use function array_unique;
use function array_values;
use function date;
use function is_array;
use function sprintf;

final class ConfigWriter extends ConfigAggregator implements ConfigWriterInterface
{
    private const CONFIG_TEMPLATE = <<<'EOT'
<?php

declare(strict_types=1);

/**
 * This configuration file was generated by %s
 * at %s
 */
 %s

EOT;

    public function __construct(
        iterable $providers = [],
        array $postProcessors = [],
        array $preProcessors = [],
        private readonly bool $deduplicateLists = true,
    ) {
        parent::__construct(
            providers: $providers,
            postProcessors: $postProcessors,
            preProcessors: $preProcessors
        );
    }

    public function writeConfig(string $targetFile): void
    {
        try {
            $merged   = $this->getMergedConfig();
            $config   = $this->deduplicateLists ? $this->deduplicateConfigLists($merged) : $merged;
            $contents = sprintf(
                self::CONFIG_TEMPLATE,
                static::class,
                date('c'),
                VarExporter::export(
                    $config,
                    VarExporter::ADD_RETURN | VarExporter::CLOSURE_SNAPSHOT_USES | VarExporter::TRAILING_COMMA_IN_ARRAY
                )
            );
        } catch (ExportException $e) {
            throw ConfigCannotBeWrittenException::fromExporterException($e);
        }

        $mode = $config[self::CACHE_FILEMODE] ?? null;

        try {
            if ($mode !== null) {
                FileWriter::writeFile($targetFile, $contents, $mode);
            } else {
                FileWriter::writeFile($targetFile, $contents);
            }
        } catch (FileWriterException $e) {
            // ignore errors writing file
            throw $e;
        }
    }

    /**
     * Recursively deduplicates PHP list arrays (integer-indexed) within a config array.
     * Prevents additive duplicates produced by array_merge_recursive when two config
     * providers both contribute the same list values.
     *
     * Associative arrays (maps) are recursed into but never deduplicated as entries.
     *
     * @param  array<mixed> $config
     * @return array<mixed>
     */
    private function deduplicateConfigLists(array $config): array
    {
        foreach ($config as $key => $value) {
            if (! is_array($value)) {
                continue;
            }
            if (array_is_list($value)) {
                $config[$key] = array_values(array_unique($value));
            } else {
                $config[$key] = $this->deduplicateConfigLists($value);
            }
        }
        return $config;
    }
}
