<?php

declare(strict_types=1);

/**
 * This configuration file was generated by Webware\ConfigManager\ConfigWriter
 * at 2026-05-26T03:24:22+00:00
 */
 return [
    'Webware\\Acl\\AclInterface' => [
        'login_path' => '/user.manager/login',
        'roles' => [
            'Guest' => [],
            'Member' => [
                'Guest',
            ],
            'Developer' => [
                'Administrator',
            ],
            'Administrator' => [
                'Member',
                'Manager',
            ],
            'Warehouse' => [
                'Member',
            ],
            'Sales' => [
                'Member',
            ],
            'Collections' => [
                'Member',
            ],
            'Warehouse Supervisor' => [
                'Warehouse',
            ],
            'Assistant Manager' => [
                'Sales',
                'Warehouse',
                'Collections',
            ],
            'Manager' => [
                'Assistant Manager',
                'Warehouse Supervisor',
            ],
        ],
        'resources' => [
            'user.manager.session.read' => true,
            'user.manager.session.create' => true,
            'user.manager.register.read' => true,
            'user.manager.register.create' => true,
            'user.manager.verify.email.read' => true,
            'user.manager.resend.verification.read' => true,
            'user.manager.resend.verification.create' => true,
            'user.manager.logout.read' => true,
            'user.manager.account.read' => true,
            'webware.admin.user.manager' => true,
            'webware.admin.user.manager.create' => true,
            'webware.admin.user.manager.update' => true,
            'webware.admin.user.manager.toggle.update' => true,
            'webware.admin.acl.manager' => null,
            'webware.admin.acl.manager.rule.create' => 'webware.admin.acl.manager',
            'webware.admin.acl.manager.rule.update' => 'webware.admin.acl.manager',
            'webware.admin.acl.manager.role.create' => 'webware.admin.acl.manager',
            'webware.admin.acl.manager.role.delete' => 'webware.admin.acl.manager',
            'webware.admin.dashboard.read' => true,
            'ims.manifest.list' => true,
            'ims.manifest.upload' => true,
            'ims.manifest.upload.store' => true,
            'ims.manifest.detail' => true,
            'admin.manifest' => true,
            'app.dashboard' => true,
            'app.api.ping' => true,
        ],
        'allow' => [
            'Guest' => [
                'user.manager.session.read' => [],
                'user.manager.session.create' => [],
                'user.manager.register.read' => [],
                'user.manager.register.create' => [],
                'user.manager.verify.email.read' => [],
                'user.manager.resend.verification.read' => [],
                'user.manager.resend.verification.create' => [],
                'app.api.ping' => [],
            ],
            'Member' => [
                'user.manager.logout.read' => [],
                'ims.manifest.list' => [],
                'ims.manifest.detail' => [],
                'app.dashboard' => [],
            ],
            'Administrator' => [
                'webware.admin.user.manager' => [],
                'webware.admin.user.manager.create' => [],
                'webware.admin.user.manager.update' => [],
                'webware.admin.user.manager.toggle.update' => [],
                'webware.admin.dashboard.read' => [],
            ],
            'Developer' => [
                'webware.admin.acl.manager' => [],
            ],
            'Warehouse' => [
                'ims.manifest.upload' => [
                    'Ims\\Store\\Acl\\StoreOwnedResourceAssertion',
                ],
                'ims.manifest.upload.store' => [
                    'Ims\\Store\\Acl\\StoreOwnedResourceAssertion',
                ],
            ],
            'Warehouse Supervisor' => [
                'admin.manifest' => [],
            ],
        ],
        'deny' => [
            'Member' => [
                'user.manager.session.read' => [],
                'user.manager.session.create' => [],
                'user.manager.register.read' => [],
                'user.manager.register.create' => [],
                'user.manager.verify.email.read' => [],
                'user.manager.resend.verification.read' => [],
                'user.manager.resend.verification.create' => [],
            ],
        ],
        'route_param_map' => [],
        'forbidden_redirect' => '/',
        'forbidden_template' => null,
        'admin_route_segment' => 'acl.manager',
        'admin_route_name_prefix' => 'acl.manager.',
    ],
];

