<?php

declare(strict_types=1);

/**
 * This configuration file was generated by Webware\ConfigManager\ConfigWriter
 * at 2026-05-19T03:58:54+00:00
 */
 return [
    'Webware\\ConfigManagerTestResource\\FooConfigProvider' => [],
];

